input:
  generate:
    mapping: |
      root = {
        "name": "pipeline 2"
      }
    interval: "0/10 * * * * *"

pipeline:
  processors:
    - resource: shared_processor

output:
  file:
    path: pipeline2.processed.json
