services:
  nats:
    build: ./nats
    image: benthos-demo/nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/nats.env
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/nats
    networks:
      - benthos-demo

  nats-configure:
    build: ./nats-configure
    image: benthos-demo/nats-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/nats-configure.env
    networks:
      - benthos-demo
    depends_on:
      - nats

  postgres:
    build: ./postgres
    image: benthos-demo/postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - benthos-demo

  minio:
    image: minio/minio
    deploy:
      restart_policy:
        condition: on-failure
    command: server /data --console-address ":9001"
    env_file:
      - ./env/minio.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - benthos-demo

  minio-configure:
    build: ./minio-configure
    image: benthos-demo/minio-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/minio-configure.env
    networks:
      - benthos-demo
    depends_on:
      - minio

  prometheus:
    build: ./prometheus
    image: benthos-demo/prometheus
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/prometheus.env
    volumes:
      - prometheus:/prometheus
    networks:
      - benthos-demo

  grafana:
    build: ./grafana
    image: benthos-demo/grafana
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/grafana.env
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - benthos-demo
    depends_on:
      - postgres
      - prometheus

  benthos1:
    build:
      context: ./benthos
      args:
        benthos_config: generate2nats.yaml
    image: benthos-demo/benthos1
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/benthos.env
    networks:
      - benthos-demo
    depends_on:
      - nats

  benthos2:
    build:
      context: ./benthos
      args:
        benthos_config: http2postgres.yaml
    image: benthos-demo/benthos2
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/benthos.env
    ports:
      - "8001:8080"
    networks:
      - benthos-demo
    depends_on:
      - postgres

  benthos3:
    build:
      context: ./benthos
      args:
        benthos_config: http2minio.yaml
    image: benthos-demo/benthos3
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/benthos.env
    ports:
      - "8002:8080"
    networks:
      - benthos-demo
    depends_on:
      - minio

networks:
  benthos-demo:
    name: benthos-demo

volumes:
  nats:
  postgres:
  minio:
  prometheus:
  grafana:
