input:
  label: fake_input
  generate:
    mapping: |
      root = {
        "name": fake("word"),
        "description": fake("paragraph"),
        "created_at": now()
      }
    interval: 5s
    batch_size: 10
    auto_replay_nacks: false

pipeline:
  processors:
    - label: archive_to_json_array
      archive:
        format: json_array

output:
  label: http_client_output
  http_client:
    url: http://fake-http-postgres-part2:8080/post
    verb: POST
    timeout: 30s
    retries: 3
    headers:
      Content-Type: application/json

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  static_fields:
    service: fake-http-postgres-part1

http:
  address: ${HTTP_ADDRESS}

shutdown_delay: 10s
