input:
  label: http_server_input
  http_server:
    path: /post
    timeout: 5s
    sync_response:
      status: ${! json("status") }
      headers: { "Content-Type": "application/json" }

pipeline:
  processors:
    - label: set_created_at_timestamp
      mapping: |
        root = this
        root.created_at = now()

output:
  fallback:
    - label: minio_output
      aws_s3:
        endpoint: ${MINIO_ENDPOINT}
        region: local
        bucket: ${MINIO_BUCKET}
        force_path_style_urls: true
        path: ${! timestamp_unix_nano() }-${! "%06d".format(count("files")) }.json
        content_type: application/json
        credentials:
          id: ${MINIO_CREDENTIALS_ID}
          secret: ${MINIO_CREDENTIALS_SECRET}
    - label: error_response
      sync_response: {}
      processors:
        - mapping: |
            root = {
              "status": 500,
              "error": "processing failed"
            }

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  static_fields:
    service: http-minio

http:
  address: ${HTTP_ADDRESS}

shutdown_delay: 10s
