global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "benthos"
    static_configs:
      - targets:
          - benthos1:8080
          - benthos2:8080
          - benthos3:8080
