global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "redpanda-connect"
    static_configs:
      - targets:
          - fake-http-postgres-part1:8080
          - fake-http-postgres-part2:8080
          - fake-nats:8080
          - http-minio:8080
