input:
  label: http_input
  http_server:
    path: /post
    timeout: 5s
    sync_response:
      status: ${! json("status") }
      headers: { "Content-Type": "application/json" }

pipeline:
  processors:
    - unarchive:
        format: json_array

output:
  fallback:
    - label: sql_output
      sql_raw:
        driver: postgres
        dsn: ${B_POSTGRES_CONNECTIONSTRING}
        batching:
          count: 1000
          period: 5s
        query: INSERT INTO task (name, description, created_at) VALUES ($1, $2, $3);
        args_mapping: |
          root = [
            this.name,
            this.description,
            this.created_at
          ]
    - label: error_response
      sync_response: {}
      processors:
        - mapping: |
            root = {
              "status": 500,
              "error": "processing failed"
            }

logger:
  level: ${B_LOG_LEVEL:INFO}
  format: logfmt
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    service: fake-http-postgres-part2

http:
  enabled: true
  address: ${B_HTTP_ADDRESS}
  debug_endpoints: false

shutdown_delay: 30s
