input:
  label: "http_input"
  http_server:
    path: /post
    timeout: 5s

pipeline:
  processors:
    - label: set_timestamp
      bloblang: |
        root = this
        root.created_at = now()

output:
  sql_raw:
    driver: postgres
    dsn: ${B_POSTGRES_CONNECTIONSTRING}
    query: INSERT INTO task (name, created_at) VALUES ($1, $2);
    args_mapping: |
      root = [
        this.name,
        this.created_at
      ]

logger:
  level: ${B_LOG_LEVEL:INFO}
  format: logfmt
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    service: demo

http:
  enabled: true
  address: ${B_HTTP_ADDRESS}
  debug_endpoints: false

shutdown_delay: 30s
