input:
  label: http_server_input
  http_server:
    path: /post
    timeout: 5s
    sync_response:
      status: ${! json("status") }
      headers: { "Content-Type": "application/json" }

pipeline:
  processors:
    - label: set_created_at_timestamp
      bloblang: |
        root = this
        root.created_at = now()

output:
  fallback:
    - label: minio_output
      aws_s3:
        endpoint: ${B_MINIO_ENDPOINT}
        region: local
        bucket: ${B_MINIO_BUCKET}
        force_path_style_urls: true
        path: ${! timestamp_unix_nano() }-${! "%06d".format(count("files")) }.json
        content_type: application/json
        credentials:
          id: ${B_MINIO_CREDENTIALS_ID}
          secret: ${B_MINIO_CREDENTIALS_SECRET}
    - label: error_response
      sync_response: {}
      processors:
        - mapping: |
            root = {
              "status": 500,
              "error": "processing failed"
            }

logger:
  level: ${B_LOG_LEVEL:INFO}
  format: logfmt
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    service: http-minio

http:
  enabled: true
  address: ${B_HTTP_ADDRESS}
  debug_endpoints: false

shutdown_delay: 30s
