input:
  label: kafka_input
  kafka_franz:
    seed_brokers:
      - ${AZURE_KAFKA_ADDRESS}
    tls:
      enabled: true
    topics:
      - ${AZURE_KAFKA_TOPIC}
    consumer_group: ${AZURE_KAFKA_CONSUMER_GROUP}
    sasl:
      - mechanism: PLAIN
        username: "$ConnectionString"
        password: ${AZURE_KAFKA_SASL_PASSWORD}

pipeline:
  processors:
    - mapping: |
        root = this
        root.processed_by = "azure-eventhub-mqtt"

output:
  label: mqtt_output
  mqtt:
    user: ${MQTT_USER}
    password: ${MQTT_PASSWORD}
    urls:
      - ${MQTT_URL}
    topic: ${MQTT_TOPIC}

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  static_fields:
    service: azure-eventhub-mqtt

http:
  address: ${HTTP_ADDRESS}

shutdown_delay: 10s
