input:
  label: http_server_input
  http_server:
    path: /post
    timeout: 30s
    sync_response:
      status: ${! json("status") }
      headers: { "Content-Type": "application/json" }

pipeline:
  processors:
    - label: unarchive_from_json_array
      unarchive:
        format: json_array

output:
  fallback:
    - label: sql_raw_output
      sql_raw:
        driver: postgres
        dsn: ${POSTGRES_CONNECTIONSTRING}
        batching:
          count: 1000
          period: 5s
        query: INSERT INTO demo.task (name, description, created_at) VALUES ($1, $2, $3);
        args_mapping: |
          root = [
            this.name,
            this.description,
            this.created_at
          ]
    - label: error_response
      sync_response: {}
      processors:
        - mapping: |
            root = {
              "status": 500,
              "error": "processing failed"
            }

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  static_fields:
    service: fake-http-postgres-part2

http:
  address: ${HTTP_ADDRESS}

shutdown_delay: 10s
